### ISSUE TITLE
Listing Organization Repositories results in Internal Server Error

### ISSUE THREAD

**Issue by geekflyer** [cirruslabs/cirrus-ci-web#91]
I'm trying to fix and enhance the organization view. The organization view header says "Repositories of X" but the list of repositories is empty. I tried fixing the graphql fragment, however all graphql queries to list the repo of an organization result in an Internal server error:

```graphql
{
githubRepositories(owner:"solvvy"){
  name
}}
```
response
```json
{
  "errors": [
    {
      "message": "Internal Server Error(s) while executing query",
      "path": null,
      "extensions": null
    }
  ],
  "data": {
    "githubRepositories": null
  }
}
```

**Comment by fkorotkov** [comment]
That's weird since https://cirrus-ci.com/github/solvvy should work and it uses [this query](https://github.com/cirruslabs/cirrus-ci-web/blob/master/src/scenes/GitHub/GitHubOrganization.tsx#L21-L29)

**Comment by geekflyer** [comment]
well. maybe it's just me getting this error, but when I click that exact URL you posted above and inspect the graphql response in the browser it's response payload contains this:

```json
{"errors":[{"message":"Internal Server Error(s) while executing query","extensions":null,"path":null}],"data":{"githubOrganizationInfo":{"role":"admin","id":"10746323"},"githubRepositories":null}}
```

I.e. it seems some data could be fetched but not the repository list.

**Comment by geekflyer** [comment]
Maybe, I should clarify and say the "query" succeeds, but the resolver for the `githubRepositories` field does not.

**Comment by fkorotkov** [comment]
Interesting. Some of the repositories under `solvvy` organization had an outdated installation id of Cirrus CI. Seems like you got it re-installed at some point. This issue should be fixed now.

**Comment by geekflyer** [comment]
Unfortunately not fixed. Still getting the same error. The org repo list on the UI stays empty.

**Comment by fkorotkov** [comment]
There was another weird issue with permissions for one of repositories for you. API though you have `none`  permissions and it got cached. Should be working now.
